# SPDX-FileCopyrightText: 2022 Emisse
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Cheackraze
# SPDX-FileCopyrightText: 2023 Checkraze
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Kesiath
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Puro
# SPDX-FileCopyrightText: 2023 Whisper
# SPDX-FileCopyrightText: 2023 coolmankid12345
# SPDX-FileCopyrightText: 2023 freeman2651
# SPDX-FileCopyrightText: 2023 ninruB
# SPDX-FileCopyrightText: 2024 AndresE55
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 Jakumba
# SPDX-FileCopyrightText: 2024 LankLTE
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 Salvantrix
# SPDX-FileCopyrightText: 2024 Shroomerian
# SPDX-FileCopyrightText: 2024 Ubaser
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2024 Wiebe Geertsma
# SPDX-FileCopyrightText: 2024 neuPanda
# SPDX-FileCopyrightText: 2025 EctoplasmIsGood
# SPDX-FileCopyrightText: 2025 Redrover1760
# SPDX-FileCopyrightText: 2025 ScyronX
# SPDX-FileCopyrightText: 2025 Your Name
# SPDX-FileCopyrightText: 2025 core-mene
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: NFDetective
  name: job-name-nf-detective
  description: job-description-nf-detective
  playTimeTracker: JobDetective
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800 # 3 hours # mono
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hours # mono
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 18000 # 5 hours # mono
  startingGear: NFDetectiveGear
  icon: JobIconNFDetective
  supervisors: job-supervisors-bailiff
  weight: 110
  displayWeight: 20
  canBeAntag: false
  guides: [ BasicLore, TransSolarFederation ] # Mono
  setPreference: false # mono
  access:
  - Detective
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: NFDetectiveGear
  equipment:
    pocket1: WeaponRevolverInspector
    pocket2: FlashlightNfsdLite
  storage:
    back:
    - Flash
    - SpeedLoader45_magnumFMJ
    - SpeedLoader45_magnumRubber
    - ForensicPad
    - ForensicScanner
    - FederationMilitaryCredit50
    - LogProbeCartridge
    - RubberStampDetective
    - ContrabandForensicsModule
